### ISSUE TITLE
Risky data exposure

### ISSUE THREAD

**Issue by conf-test** [MenloSystems/docker-mediawiki#1]
Hi,

I'm a security researcher and am doing some study of public docker images. I found some misconfigurations in your this image that may expose some risky data at runtime. The exposure I found include:

git:
/extensions/Popups/.gitattributes
/extensions/Math/.gitattributes
/extensions/LDAPUserInfo/.gitignore 
/extensions/LDAPUserInfo/.gitreview
/extensions/Popups/gitinfo.json                 
/extensions/LDAPAuthentication2/.gitignore          
/extensions/LDAPAuthorization/.gitreview        

phpunit:
/extensions/LDAPAuthorization/tests/phpunit/*
/extensions/Math/tests/phpunit/*
/extensions/Popups/tests/phpunit/*

composer:
/extensions/LDAPUserInfo/vendor/composer/*
/extensions/LDAPAuthorization/vendor/composer/*
/extensions/LDAPAuthentication2/vendor/composer/*

Here are some reference about these exposures:
https://iosentrix.com/blog/git-source-code-disclosure-vulnerability/
https://stackoverflow.com/questions/11078572/should-i-use-phpunit-in-a-staging-production-environment
bolt/bolt#375
wp-cli/doctor-command#98

If you want, I can also help fix them. Please let me know what you think. Thanks!

Best,
~cf

**Comment by olafmandel** [comment]
Thank you for your message. For us, none of these are a problem: we only use the image in our intranet, so no problem. Will add a note about the status of this image to the README for others to see, as well. As for the details:

* `**/.git{attributes,ignore,review}` and `**/gitinfo.json`: are you serious? Listing these under the heading of "git source code disclosure vulnerability" is borderline [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt). These are all unmodified files from public plugins, not even the actual `.git` repos. The worst that this would "expose" is where those (FOSS!) plugins do their code-reviews and what hashes are used here
* `**/phpunit/*`: ACK, this may well be an opportunity for a [DoS](https://en.wikipedia.org/wiki/Denial-of-service_attack) if remote users manage to trigger long-running tests. If those tests are badly written (not self-contained, exposing internals of the file-system, ...) it might be more. I didn't manage to trigger a single test, but that might be me...
* `*/composer/*`: again, some code that should not be executable.

I guess the best solution is to disable code executation for the unwanted directories.
